apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-depl
  labels:
    app: password
spec:
  replicas: 2
  selector:
    matchLabels:
      app: password
  template:
    metadata:
      labels:
        app: password
    spec:
      containers:
      - name: password
        image: cutomer-serve
        ports:
        - containerPort:
        ---
apiVersion: v1
kind: Service
metadata:
  name: password-service
  labels:
    app: password
spec:
  selector:
    app: password
  type: NodePort
  ports:
  - port: 80
    nodePort: 31364
    targetPort: 8006
    protocol: TCP
    name: http