apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: postresql
        ports:
        - containerPort: https://console.cloud.google.com/storage/browser/mage-zoomcamp-mage-matt-palmer-3
        ---
apiVersion: v1
kind: Service
metadata:
  name: productdb-service
  labels:
    app: productdb
spec:
  selector:
    app: productdb
  type: NodePort
  ports:
  - port: 80
    nodePort: 31364
    targetPort: 8006
    protocol: TCP
    name: http